baseURL = "https://josephsaffron.github.io/"
languageCode = "en-us"
title = "him.happyhippos"
theme = "Hugo-Octopress"

[permalinks]
    post = "/blog/:year-:month-:day-:title/"

[params]
    author = "Joseph Wong"
    github = "https://github.com/josephsaffron/"
    twitter = "https://twitter.com/yellowedjoe"
    sidebarHeader = "About Me"
    sidebarText = "Father of two, software developer, avid reader"
    sidebarRecentLimit = 3
